const ENVS = {
  COMPANY_NAME: process.env.REACT_APP_COMPANY_NAME,
  COMPANY_EMAIL: process.env.REACT_APP_COMPANY_EMAIL,
  STORE_LOCATION: process.env.REACT_APP_STORE_LOCATION,
  OFFICE_LOCATION: process.env.REACT_APP_OFFICE_LOCATION,
  COMPANY_PHONE_NUMBER: process.env.REACT_APP_COMPANY_PHONE_NUMBER,
  WORK_HOURS: process.env.REACT_APP_WORK_HOURS,
  FACEBOOK_URL: process.env.REACT_APP_FACEBOOK_URL,
  INSTAGRAM_URL: process.env.REACT_APP_INSTAGRAM_URL,
};

export default ENVS;
